Fix space-delimited NOAA ODP files.

Use R readr instead of Python pandas because  readr::read_table handles the space-delimited file better than pandas.

```{r}
library(readr)
library(tidyverse)
```

# Convert space-delimited file into csv

```{r}
raw_file = './raw_data/odp_all_paleontology/range_tables/149/897/HOLE_C/Nannofossils.txt'
file = './cleaned_data/odp_all_paleontology/range_tables/149/897/HOLE_C/Nannofossils.txt'
```

```{r}
data1 <- readr::read_table(raw_file, col_names=FALSE, col_types = cols(.default = "c"), n_max=1)

```

```{r}
columns <- as.character(data1[1,])
columns
```


```{r}
# read all columns as charcters
data <- readr::read_table(raw_file, col_types = cols(.default = "c"))

```

```{r}
for (col in colnames(data)) {
   print(gsub('_[0-9]+$', '', col))
}
 

```



```{r}
data %>% unite('Age To (youngest)',  c('Age', 'To', '(youngest)'), sep='')
```

```{r}
readr::write_tsv(data, file, na='', )
```



# Convert space-delimited file into csv

After manually fix the column names, use R to clean the file.

```{r}
revised_data <- readr::read_tsv(file)
```

Remove blank columns that read_table automatically added 
```{r}
fixed_data = revised_data[,!grepl("^X[0-9]+$",names(revised_data))]
```

update file

```{r}
readr::write_tsv(fixed_data, file)
```
